version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    groups:
      google-ads-api:
        patterns:
          - github.com/shenzhencenter/google-ads-pb
      go-minor-and-patch:
        exclude-patterns:
          - github.com/shenzhencenter/google-ads-pb
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
